#!/bin/bash -e

cd container

sudo apt update
sudo apt install -y dos2unix

dos2unix bin/*

echo $dockerhubkey | docker login --username $dockerusername --password-stdin
docker buildx create --use --name builder --platform linux/amd64,linux/arm/v7,linux/arm64/v8,linux/arm/v6
docker buildx build -t pthoelken/fritzbox-zabbix-monitoring:$1 --push --force-rm --no-cache --platform linux/amd64,linux/arm/v7,linux/arm64/v8,linux/arm/v6 -f Dockerfile .