services:
  fritzbox-monitor:
    image: pthoelken/fritzbox-zabbix-monitoring:${VERSION}
    container_name: fritzbox-zabbix-monitoring
    restart: unless-stopped
    env_file:
      - .env
    #volumes:
    #  - ./zabbix.psk:/run/secrets/zabbix_psk:ro